version: '3'
services:
  node:
    # restart: always
    build: .
    ports:
      - 80:3000
    volumes:
      - .:/app
    environment:
      - MONGO_URL=mongodb://mongo:27017
  
  mongo:
    image: mongo:6.0.6-jammy
    ports:
      - 27017:27017
